# Generated by Django 4.1 on 2022-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customers", "0002_alter_customers_customer_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="customer_address",
            field=models.CharField(default="", max_length=100),
        ),
    ]
