# Generated by Django 4.0.3 on 2022-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_customers_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
