# Generated by Django 4.1 on 2022-09-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Customers", "0002_alter_customers_customer_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.CharField(max_length=50)),
                ("Pos_no", models.CharField(max_length=50)),
                ("month", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("address", models.CharField(max_length=50)),
                ("account_of", models.CharField(max_length=50)),
                ("amount", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField(blank=True, null=True)),
                ("net_amount", models.PositiveIntegerField()),
                ("remarks", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Customers.customers",
                    ),
                ),
            ],
        ),
    ]
