# Generated by Django 4.1 on 2022-09-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sales", old_name="Pos_no", new_name="PoS_no",
        ),
        migrations.RemoveField(model_name="sales", name="customer_id",),
    ]
