# Generated by Django 4.0.3 on 2022-09-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_customers_customer_file'),
        ('Sales', '0002_rename_pos_no_sales_pos_no_remove_sales_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.customers'),
        ),
    ]
