# Generated by Django 4.1 on 2022-09-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0004_alter_sales_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rv_no", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("amount", models.PositiveIntegerField()),
                (
                    "bill_remarks",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reason", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sales_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Sales.sales",
                    ),
                ),
            ],
        ),
    ]
