# Generated by Django 4.0.3 on 2022-09-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_bills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='sales_id',
            new_name='sale_id',
        ),
    ]
