# Generated by Django 4.1 on 2022-09-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0006_rename_bills_bill_rename_sales_id_bill_sale_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="sale_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Sales.sales"
            ),
        ),
    ]
