# Generated by Django 4.0 on 2022-09-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_alter_bill_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('complementery', 'Complementery'), ('cancel', 'Cancel')], max_length=50, null=True),
        ),
    ]
