# Generated by Django 4.0.3 on 2022-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rv_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
