# Generated by Django 4.0.3 on 2022-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_alter_bill_amount_alter_bill_rv_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.AddField(
            model_name='sales',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
