# Generated by Django 4.1 on 2022-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0013_sales_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
