# Generated by Django 4.0.3 on 2022-10-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0015_dummytable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummytable',
            old_name='name',
            new_name='cname',
        ),
    ]
