# Generated by Django 4.0.3 on 2022-10-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_alter_dummytable_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='month',
            field=models.DateField(),
        ),
    ]
