# Generated by Django 4.0.3 on 2022-10-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0024_alter_dummytable_month_alter_sales_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytable',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
