# Generated by Django 4.0.3 on 2022-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0025_alter_dummytable_month_alter_sales_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
