# Generated by Django 4.1 on 2022-10-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0027_alter_dummytable_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid", "Paid"),
                    ("complementery", "Complementery"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
