# Generated by Django 4.1 on 2022-11-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0028_alter_bill_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="sale_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Sales.sales"
            ),
        ),
    ]
